import { Transaction, TransactionType, Category } from "@/lib/types";

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    amount: 5000,
    category: Category.SALARY,
    date: "2023-10-01",
    notes: "Monthly salary",
    type: TransactionType.INCOME,
  },
  {
    id: "2",
    amount: 120,
    category: Category.FOOD,
    date: "2023-10-02",
    notes: "Grocery shopping",
    type: TransactionType.EXPENSE,
  },
  {
    id: "3",
    amount: 45,
    category: Category.TRANSPORT,
    date: "2023-10-03",
    notes: "Uber ride",
    type: TransactionType.EXPENSE,
  },
  {
    id: "4",
    amount: 1200,
    category: Category.HOUSING,
    date: "2023-10-05",
    notes: "Rent payment",
    type: TransactionType.EXPENSE,
  },
  {
    id: "5",
    amount: 300,
    category: Category.FREELANCE,
    date: "2023-10-10",
    notes: "Logo design project",
    type: TransactionType.INCOME,
  },
  {
    id: "6",
    amount: 85,
    category: Category.ENTERTAINMENT,
    date: "2023-10-12",
    notes: "Movie night",
    type: TransactionType.EXPENSE,
  },
  {
    id: "7",
    amount: 60,
    category: Category.SHOPPING,
    date: "2023-10-15",
    notes: "New shirt",
    type: TransactionType.EXPENSE,
  },
];
